apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-studentportal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-studentportal
  template:
    metadata:
      labels:
        app: mern-studentportal
    spec:
      containers:
      - name: mern-studentportal
        image: docker.io/kiruthik1304/mern-studentportal:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mern-studentportal-service
spec:
  type: NodePort
  selector:
    app: mern-studentportal
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
